server:
  port: 8280
spring:
  application:
    name: reader-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    '[org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker]': error